src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use App\Util\ViewCode;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Finder\Exception\AccessDeniedException;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Unique;
use Symfony\Component\Validator\Mapping\ClassMetadata;
use App\Entity\Traits\TimeStampableTrait;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Table(name="`user`")
 */
class User implements UserInterface
{

    use TimeStampableTrait;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=250)
     */
    private $roles = "";

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\ManyToMany(targetEntity=Band::class, mappedBy="members")
     */
    private $bands;

    public function __construct()
    {
        $this->bands = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = explode(',', $this->roles);
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return $roles;
    }

    public function setRoles(array $roles): self
    {
        $this->roles = implode(",", $roles);

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Band[]
     */
    public function getBands(): Collection
    {
        return $this->bands;
    }

    public function addBand(Band $band): self
    {
        if (!$this->bands->contains($band)) {
            $this->bands[] = $band;
            $band->addMember($this);
        }

        return $this;
    }

    public function removeBand(Band $band): self
    {
        if ($this->bands->contains($band)) {
            $this->bands->removeElement($band);
            $band->removeMember($this);
        }

        return $this;
    }

    public function requireMemberOf(Band $band)
    {
        if (!$this->bands->contains($band))
            throw new AccessDeniedException("User is not a member of this band!");
    }



    // For BandType Validation

    public static function loadValidatorMetadata(ClassMetadata $metadata)
    {
        $metadata->addPropertyConstraint('email', new NotBlank());
        $metadata->addPropertyConstraint('email', new Email());
        $metadata->addConstraint(new UniqueEntity([
            'fields' => 'email',
            'message' => 'An account is already linked with this email'
        ]));

        $metadata->addPropertyConstraint('password', new NotBlank());
        $metadata->addPropertyConstraint('password', new Length([
            'min' => 5,
            'max' => 10,
            'minMessage' => 'Password must be at least {{ limit }} characters long',
            'maxMessage' => 'Password cannot be longer than {{ limit }} characters',
            'allowEmptyString' => false,
        ]));
    }

    public function getViewCode()
    {
        return ViewCode::codeFromId(ViewCode::idFromCode(ViewCode::codeFromId($this->getId())));
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\FormUtils;
use App\Form\UserType;
use App\Security\LoginFormAuthenticator;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Guard\GuardAuthenticatorHandler;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

class SecurityController extends AbstractController
{
    /**
     * @Route("/", name="app_home")
     */
    public function home(): Response
    {
        if ($this->getUser())
            return $this->redirectToRoute('bands_all');

        return $this->render('security/home.html.twig', []);
    }

    /**
     * @Route("/sign-up", name="app_sign_up")
     */
    public function signUp(Request $request, UserPasswordEncoderInterface $passwordEncoder, GuardAuthenticatorHandler $guardHandler, LoginFormAuthenticator $formAuthenticator): Response
    {
        $user = new User();

        $form = $this->createForm(UserType::class, $user, [
            "submit_label" => "Create your account",
            "repeat_password" => true
        ]);

        if (FormUtils::updateDBIfValid($request, $form, $this->getDoctrine()->getManager())) {

            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $user->getPassword()
                )
            );

            $objectManager = $this->getDoctrine()->getManager();
            $objectManager->persist($user);
            $objectManager->flush();

            $request->query->set('user', $user);

            return $guardHandler->authenticateUserAndHandleSuccess(
                $user,
                $request,
                $formAuthenticator,
                'main'
            );
        }

        return $this->render('security/signUp.html.twig', [
            'form' => $form->createView()
        ]);
    }


    /**
     * @Route("/my-account", name="app_account_edit")
     * @IsGranted("ROLE_USER")
     **/

    public function myAccount(Request $request, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $user = $this->getUser();
        $form = $this->createForm(UserType::class, $user, [
            "submit_label" => "Modify",
            "repeat_password" => true
        ]);

        $objectManager = $this->getDoctrine()->getManager();

        if (FormUtils::updateDBIfValid($request, $form, $objectManager)) {

            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $user->getPassword()
                )
            );

            $objectManager->persist($user);
            $objectManager->flush();

            return $this->redirectToRoute('app_home');
        }

        return $this->render('security/myAccount.html.twig', [
            'form' => $form->createView(),
            'user' => $user
        ]);
    }


    /**
     * @Route("/login", name="app_login")
     */
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        if ($this->getUser())
            return $this->redirectToRoute('bands_all');

        $user = new User();
        $user->setEmail($authenticationUtils->getLastUsername());

        $form = $this->createForm(UserType::class, $user, [
            "submit_label" => "Sign in",
            "repeat_password" => false
        ]);

        return $this->render('security/login.html.twig', [
            'error' => $authenticationUtils->getLastAuthenticationError(),
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/logout", name="app_logout")
     */
    public function logout()
    {
        throw new \LogicException(
            'This method can be blank - it will be intercepted by the logout key on your firewall.'
        );
    }
}

templates/security/home.html.twig
{% extends 'base.html.twig' %}

{% block verticallyCenter %}

	<div class="card">
		<div class="card-body rounded border border-primary">
			<h1 class="card-title">Tabs@app</h1>
			<p class="card-text">
				Gérez vos groupes de musiques, vos morceaux et vos tablatures.
									                            Une application gratuite destinée à tous les musiciens.
			</p>
			<div class="d-flex justify-content-end align-items-center">
				<a href="{{ path('app_sign_up') }}" class="btn btn-primary mr-3">
					Sign Up
				</a>
				<a href="{{ path('app_login') }}" class="btn btn-primary">
					Login
				</a>
			</div>
		</div>
	</div>

{% endblock %}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block verticallyCenter %}
	<div class="card">
		<div class="card-body rounded border border-primary">
			<h1 class="card-title mb-5 d-flex align-items-center">
				<ion-icon name="arrow-forward-circle-outline" class="d-sm-inline d-none mr-2"></ion-icon>
				<span>
					Login to tabs@app!</span>
			</h1>

			<div class="form">
				{{ form_start(form) }}

				{% if app.user %}
					<div class="mb-3">
						You are logged in as
						{{ app.user.username }},
						<a href="{{ path('app_logout') }}">Logout</a>
					</div>
				{% endif %}

				{% if error %}
					<div class="alert alert-danger">
						{{ error.messageKey|trans(error.messageData, 'security') }}
					</div>
				{% endif %}

				{{ form_errors(form) }}

				{{ form_row(form.email) }}
				{{ form_row(form.password) }}

				<input type="hidden" name="user[_csrf_token]" value="{{ csrf_token('authenticate') }}">


				{# Uncomment this section and add a remember_me option below your firewall to activate remember me functionality. #}
				{# See https://symfony.com/doc/current/security/remember_me.html #}

				{# <div class="checkbox mb-3">
											<label>
												<input type="checkbox" name="user[_remember_me]">
												Remember me
											</label>
										</div> #}


				{{ form_row(form.save) }}
			{{ form_end(form) }}
			</div>
				<div class="d-flex justify-content-end mt-2"> <a href="{{ path('app_forgot_password_request') }}">
					I forgot my password
				</a>
			</div>
		</div>
	</div>

{% endblock %}

templates/security/myAccount.html.twig
{% extends 'base.html.twig' %}

{% block verticallyCenter %}
	<div class="card">
		<div class="card-body rounded border border-primary">
			<h1 class="card-title mb-5 d-flex align-items-center">
				<ion-icon name="people-outline" class="d-sm-inline d-none mr-2"></ion-icon>
				<span>
					My account
					{{ user.viewCode }}
				</span>
			</h1>
			<div class="form">
				{{ form(form) }}
			</div>
		</div>
	</div>

{% endblock %}

templates/security/signUp.html.twig
{% extends 'base.html.twig' %}

{% block verticallyCenter %}

	<div class="card">
		<div class="card-body rounded border border-primary">
			<h1 class="card-title mb-5 d-flex align-items-center">
				<ion-icon name="arrow-forward-circle-outline" class="d-sm-inline d-none"></ion-icon>
				<span>
					Let's create your account!
				</span>
			</h1>
			<div class="form">
				{{ form(form) }}
			</div>
		</div>
	</div>

{% endblock %}