src/Entity/Song.php
<?php

namespace App\Entity;

use App\Repository\SongRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Finder\Exception\AccessDeniedException;
use Symfony\Component\Validator\Mapping\ClassMetadata;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Length;
use App\Entity\Traits\TimeStampableTrait;

/**
 * @ORM\Entity(repositoryClass=SongRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Table(name="`song`")
 */
class Song
{

    use TimeStampableTrait;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Band::class, inversedBy="songs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $band;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $capo;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $song_name;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $group_name;

    /**
     * @ORM\Column(type="text")
     */
    private $guitar_tabs;

    /**
     * @ORM\ManyToOne(targetEntity=Tag::class, inversedBy="songs")
     */
    private $tag;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $lyrics;

    public function __construct()
    {
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getBand(): ?Band
    {
        return $this->band;
    }

    public function setBand(?Band $band): self
    {
        $this->band = $band;

        return $this;
    }

    public function getCapo(): ?string
    {
        return $this->capo;
    }

    public function setCapo(string $capo): self
    {
        $this->capo = $capo;

        return $this;
    }

    public function getSongName(): ?string
    {
        return $this->song_name;
    }

    public function setSongName(string $song_name): self
    {
        $this->song_name = $song_name;

        return $this;
    }

    public function getGroupName(): ?string
    {
        return $this->group_name;
    }

    public function setGroupName(string $group_name): self
    {
        $this->group_name = $group_name;

        return $this;
    }

    // For BandType Validation

    public static function loadValidatorMetadata(ClassMetadata $metadata)
    {
        $metadata->addPropertyConstraint('capo', new NotBlank());
        $metadata->addPropertyConstraint('song_name', new NotBlank());
        $metadata->addPropertyConstraint('group_name', new NotBlank());
        $metadata->addPropertyConstraint('guitar_tabs', new NotBlank());

        $metadata->addPropertyConstraint('capo', new Length([
            'min' => 1,
            'max' => 10,
            'minMessage' => 'Capo must be at least {{ limit }} characters long',
            'maxMessage' => 'Capo cannot be longer than {{ limit }} characters',
            'allowEmptyString' => false,
        ]));

        $metadata->addPropertyConstraint('song_name', new Length([
            'min' => 1,
            'max' => 30,
            'minMessage' => 'Song name must be at least {{ limit }} characters long',
            'maxMessage' => 'Song name cannot be longer than {{ limit }} characters',
            'allowEmptyString' => false,
        ]));

        $metadata->addPropertyConstraint('group_name', new Length([
            'min' => 1,
            'max' => 30,
            'minMessage' => 'Group name must be at least {{ limit }} characters long',
            'maxMessage' => 'Group name name cannot be longer than {{ limit }} characters',
            'allowEmptyString' => false,
        ]));

        $metadata->addPropertyConstraint('guitar_tabs', new Length([
            'min' => 0,
            'max' => 10000,
            'minMessage' => 'Partition content must be at least {{ limit }} characters long',
            'maxMessage' => 'Partition content cannot be longer than {{ limit }} characters',
            'allowEmptyString' => true,
        ]));

        $metadata->addPropertyConstraint('lyrics', new Length([
            'min' => 0,
            'max' => 10000,
            'minMessage' => 'Lyrics content be at least {{ limit }} characters long',
            'maxMessage' => 'Lyrics content name cannot be longer than {{ limit }} characters',
            'allowEmptyString' => true,
        ]));
    }

    public function requireSongOf(Band $band)
    {
        if ($this->band != $band)
            throw new AccessDeniedException("Band does not contains this song!");
    }

    public function getGuitarTabs(): ?string
    {
        return $this->guitar_tabs;
    }

    public function setGuitarTabs(string $guitarTabs): self
    {
        $this->guitar_tabs = $guitarTabs;

        return $this;
    }

    public function getTag(): ?Tag
    {
        return $this->tag;
    }

    public function setTag(?Tag $tag): self
    {
        $this->tag = $tag;

        return $this;
    }

    public function getLyrics(): ?string
    {
        return $this->lyrics;
    }

    public function setLyrics(?string $lyrics): self
    {
        $this->lyrics = $lyrics;

        return $this;
    }
}

src/Form/SongType.php
<?php

namespace App\Form;

use App\Entity\Song;
use App\Entity\Tag;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class SongType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('song_name', TextType::class, [
                'required' => true
            ])
            ->add('group_name', TextType::class, [
                'required' => true
            ])
            ->add('capo', TextType::class, [
                'required' => true
                // 'data' => 'Aucun'
            ])
            ->add('guitar_tabs', TextareaType::class, [
                'required' => true,
                'attr' => [
                    'rows' => 5
                ]
            ])
            ->add('lyrics', TextareaType::class, [
                'required' => true,
                'attr' => [
                    'rows' => 5
                ]
            ])
            ->add('tag', EntityType::class, [
                'required' => true,
                'class' => Tag::class,
                'choice_label' => function ($tag) {
                    return $tag->getLabel();
                }
            ])
            ->add('save', SubmitType::class, [
                'label' => $options['submit_label']
            ]);;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Song::class,
            'submit_label' => "Undefined label title"
        ]);

        $resolver->setAllowedTypes('submit_label', 'string');
    }
}

src/Controller/SongController.php
<?php

namespace App\Controller;

use App\Entity\Band;
use App\Entity\Song;
use App\Form\FormUtils;
use App\Form\SongType;
use App\Form\TagType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @IsGranted("ROLE_USER")
 * @Route("/bands/{band}/songs", name="songs_", requirements={"band"="\d+"})
 */
class SongController extends AbstractController
{

    /**
     * @Route("/{song}", name="one", requirements={"song"="\d+"})
     */
    public function one(Band $band, Song $song)
    {
        $this->getUser()->requireMemberOf($band);
        $song->requireSongOf($band);

        return $this->render('song/one.html.twig', [
            'band' => $band,
            'song' => $song,
            'tabs' => [
                [
                    'id' => 'guitar',
                    'title' => 'Guitar',
                    'content' => $song->getGuitarTabs()
                ],
                [
                    'id' => 'lyrics',
                    'title' => 'Lyrics',
                    'content' => $song->getLyrics()
                ]
            ]
        ]);
    }

    /**
     * @Route("/create", name="create")
     */
    public function create(Request $request, Band $band)
    {
        $this->getUser()->requireMemberOf($band);

        $song = new Song();
        $song->setBand($band);

        $form = $this->createForm(SongType::class, $song, ["submit_label" => "Create"]);

        if (FormUtils::updateDBIfValid($request, $form, $this->getDoctrine()->getManager()))
            return $this->redirectToRoute('songs_one', [
                'band' => $band->getId(),
                'song' => $song->getId()
            ]);

        return $this->render('song/create.html.twig', [
            'band' => $band,
            'song' => $song,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/{song}/edit", name="edit", requirements={"song"="\d+"})
     */
    public function edit(Request $request, Band $band, Song $song)
    {
        $this->getUser()->requireMemberOf($band);
        $song->requireSongOf($band);

        $form = $this->createForm(SongType::class, $song, ["submit_label" => "Modify"]);

        if (FormUtils::updateDBIfValid($request, $form, $this->getDoctrine()->getManager()))
            return $this->redirectToRoute('songs_one', [
                'band' => $band->getId(),
                'song' => $song->getId(),
            ]);

        return $this->render('song/edit.html.twig', [
            'band' => $band,
            'song' => $song,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/{song}/delete", name="delete", requirements={"song"="\d+"})
     */
    public function delete(Band $band, Song $song)
    {
        $this->getUser()->requireMemberOf($band);
        $song->requireSongOf($band);

        $band = $song->getBand();

        $objectManager = $this->getDoctrine()
            ->getManager();
        $objectManager->remove($song);
        $objectManager->flush();

        return $this->redirectToRoute('bands_one', [
            'band' => $band->getId()
        ]);
    }
}

templates/song/all.html.twig
{% extends 'base.html.twig' %}

{% block verticallyCenter %}

	<div class="card">
		<div class="card-body rounded border border-primary">
			<h1 class="card-title mb-5 d-flex align-items-center">
				<ion-icon name="musical-notes-outline" class="d-sm-inline d-none mr-2"></ion-icon>
				<span>Band :
					{{ band.name }}</span>
			</h1>
			<div class="mb-2 d-flex flex-sm-row flex-column justify-content-between align-items-sm-center align-items-start">
				<div class="d-sm-block d-flex flex-column">
					<a href="{{ path('bands_edit', { band : band.id }) }}" class="mr-2">
						Rename
					</a>
					<a href="{{ path('members_manage', { band : band.id }) }}" class="mr-2">
						Members
					</a>
					<a href="{{ path('bands_stats', { band : band.id }) }}" class="mr-2">
						Statistics
					</a>
				</div>
				<a class="mr-2" href="{{ path('songs_create', { band : band.id }) }}">
					Add a song
				</a>
			</div>
			<div>
				{% if band.songs|length == 0 %}
					<p>
						You don't have any songs!
					</p>
				{% else %}

					<form id="pagination-form" method="POST">

						<div class="input-group mb-3">
							<div class="input-group-prepend">

								<span class="input-group-text" id="inputGroup-sizing-default">
									<ion-icon name="search-outline"></ion-icon>
								</span>
							</div>
							<input type="text" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" name="song_search" placeholder="Search" value="{{ search }}">
						</div>
						{% if songs|length == 0 %}
							<p>
								No sound matches with your request!
							</p>
						{% else %}
							<ul class="list-group">
								{% for song in songs %}
									<li onclick="location.href = '{{ path('songs_one', { song : song.id, band : song.band.id }) }}';" class="list-group-item d-flex justify-content-between align-items-center clickable-el">
										
										<span class="d-flex align-items-center">
											<ion-icon name="musical-note-outline" class="mr-3"></ion-icon>
											<span>
												{{ song.songName|e }},
												{{ song.groupName|e }}
											</span>
										</span>

										{% if song.tag is defined and song.tag is not null %}
											<div>
												<a class="notification">
													<span style="background-color : {{ song.tag.color }};" class="px-2 py-2 badge badge-primary badge-pill">
														{{ song.tag.label }}
													</span>
												</a>
											</div>
										{% endif %}
										
									</li>
								{% endfor %}
							</ul>
							{{ include('components/pagination.html.twig', { items: songs}) }}
						{% endif %}
					</form>
				{% endif %}
			</div>

		</div>
	</div>

{% endblock %}

{% block javascripts %}

	{{ parent() }}
	{{ encore_entry_script_tags('js/pagination') }}

{% endblock %}

templates/song/create.html.twig
{% extends 'base.html.twig' %}

{% block verticallyCenter %}

	<div class="card">
		<div class="card-body rounded border border-primary">
			<h1 class="card-title mb-5 d-flex align-items-center">
				<ion-icon name="arrow-forward-circle-outline" class="d-sm-inline d-none mr-2"></ion-icon>
				<span>
					Let's create a song!</span>
			</h1>
			<div class="form">
				{{ form(form) }}
			</div>
		</div>
	</div>

{% endblock %}

templates/song/edit.html.twig
{% extends 'base.html.twig' %}
{% block verticallyCenter %}
	<div class="card">
		<div class="card-body rounded border border-primary">
			<h1 class="card-title mb-4 d-flex align-items-center">
				<ion-icon name="arrow-forward-circle-outline" class="d-sm-inline d-none mr-2"></ion-icon>
				<span>
					Edit :
					{{ song.songName|e}}
				</span>
			</h1>
			{{ form_start(form) }}
			{{ form_errors(form) }}
			{{ form_row(form.song_name) }}
			{{ form_row(form.group_name) }}
			{{ form_row(form.tag) }}
			{{ form_row(form.capo) }}
			{{ form_row(form.guitar_tabs) }}
			{{ form_row(form.lyrics) }}
			<div class="d-flex justify-content-end">
				{{ form_widget(form.save) }}
				<button type="button" class="ml-3 btn btn-danger d-flex align-items-center" data-toggle="modal" data-target="#confirmModal">
					<ion-icon class="mr-1" name="alert-circle-outline"></ion-icon>
					<span>Delete
					</span>
				</button>
			</div>
			{{ form_end(form) }}
		</div>
	</div>
	<div class="modal fade" id="confirmModal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="modalLabel">Are you sure ?
					</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;
						</span>
					</button>
				</div>
				<div class="modal-body">
					You are going to delete definitively the song.
				</div>
				<div class="modal-footer">
					<button class="btn btn-danger" onclick="location.href = '{{ path('songs_delete', { song : song.id, band : song.band.id }) }}';">
						Yes
					</button>
					<button type="button" class="btn btn-primary" data-dismiss="modal">No
					</button>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/song/one.html.twig
{% extends 'base.html.twig' %}

{% block verticallyCenter %}


	<div class="card">
		<div class="card-body rounded border border-primary">
			<h1 class="card-title d-flex align-items-center">
				<ion-icon name="musical-notes-outline" class="d-sm-inline d-none mr-2"></ion-icon>
				<span>
					Song : {{ song.songName }}
				</span>
			</h1>
			<h2 class="text-muted">
				{{ song.groupName }}
			</h2>
			<h3 class="my-2">
				Capo : {{ song.capo }}
			</h3>
			{% if song.tag is defined and song.tag is not null %}
				<span style="background-color : {{ song.tag.color }};" class="mt-2 mb-4 px-2 py-2 badge badge-primary badge-pill">
					{{ song.tag.label }}
				</span>	
			{% endif %}

			<div class="d-flex justify-content-between align-items-center">
				<ul class="nav nav-tabs">

					{% for tab in tabs %}

						<li class="nav-item">
							<a href="#{{ tab.id }}" class="nav-link" data-toggle="tab">
								{{ tab.title }}
							</a>
						</li>

					{% endfor %}
				</ul>
				<span>
					<a href="{{ path('songs_edit', { song : song.id, band : song.band.id }) }}">
						Edit the song
					</a> 
				</span>
			</div>

			<div class="tab-content">
				
				{% for tab in tabs %}

					<div class="tab-pane fade" id="{{ tab.id }}">
						<div class="card-body">
							<p class="card-text">
								{{ tab.content | nl2br }}
							</p>
						</div>
					</div>

				{% endfor %}
				
			</div>
			
		</div>
	</div>

{% endblock %}

{% block javascripts %}

	{{ parent() }}
	{{ encore_entry_script_tags('js/tabs') }}

{% endblock %}